log:
  level: INFO

api:
  dashboard: true
  insecure: true

ping:
  entryPoint: traefik

entryPoints:
  traefik:
    address: "192.168.1.50:8080"
  web:
    address: "203.0.113.10:80"
  websecure:
    address: "203.0.113.10:443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@example.com
      storage: /var/lib/traefik/acme.json
      httpChallenge:
        entryPoint: web
